services:
# 1. Servicio de Base de Datos PostgreSQL
  db:
    image: postgres:15
    container_name: macuin_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: autopartes_db
    ports:
      - "5432:5432"
    volumes:
      # Postgres guarda los datos en esta ruta interna
      - db_data:/var/lib/postgresql/data
      # IMPORTANTE: He comentado tu init-db temporalmente. 
      # (El código SQL de MySQL no es 100% compatible con Postgres y podría crashear el arranque).
      # - ./init-db:/docker-entrypoint-initdb.d 
    restart: always

# 2. Servicio de nuestra API FastAPI
  api_central:
    build: ./api_central
    container_name: macuin_api
    ports:
      - "8000:8000"
    environment:
      # Actualizamos la URL para que apunte al nuevo contenedor de Postgres
      - DATABASE_URL=postgresql://admin:123456@db:5432/autopartes_db
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./api_central:/app
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
    restart: always

  # Servicio de flask
  flask_admin:
    build: ./flask_admin
    container_name: macuin_flask_admin
    ports:
      - "5002:5000"
    environment:
      # Aquí conectamos Flask con la API a través de la red interna de Docker
      - API_URL=http://api_central:8000
      - SECRET_KEY=una_clave_super_secreta_para_sesiones
      - FLASK_DEBUG=1
    volumes:
      - ./flask_admin:/app
    depends_on:
      - api_central
    restart: always

  # Servicio de Laravel
  laravel_cliente:
    build:
      context: ./laravel_cliente
      dockerfile: Dockerfile
    container_name: macuin_laravel_cliente
    restart: unless-stopped
    ports:
      # CAMBIO: Usaremos el 8080 para no chocar con tu API FastAPI que usa el 8000
      - "8080:80"
    environment:
      - API_URL=http://api_central:8000
    volumes:
      # Sincroniza tu código local con el contenedor para desarrollo en vivo
      - ./laravel_cliente:/var/www/html
    command: >
      sh -c "chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache
             && chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
             && sed -i \"s/listen 80/listen $${PORT:-80}/g\" /etc/nginx/http.d/default.conf
             && php-fpm -D && nginx -g 'daemon off;'"
    depends_on:
      - api_central

# Volumen para que los datos de MySQL no se borren si apagamos el contenedor
volumes:
  db_data:
  